from __future__ import annotations

import json
from pathlib import Path


REQUIRED_DOCS = [
    "01_visao.md",
    "02_requisitos.md",
    "03_regras_de_negocio.md",
    "04_fluxos.md",
    "05_arquitetura.md",
    "06_modelo_dados.md",
    "07_api.md",
    "08_seguranca.md",
    "09_riscos.md",
    "10_backlog.md",
    "11_validacao.md",
    "12_roadmap.md",
    "13_deploy.md",
    "14_observability.md",
    "15_security_threats.md",
    "16_release_notes.md",
    "27_descoberta_guiada.md",
    "28_validacao_pre_kickoff.md",
    "31_politica_decisao_comercial.md",
    "32_programa_treinamento_agentes.md",
    "33_scorecard_agentes.md",
]

TEMPLATE_PACKET_FILES = [
    "00_intake_proposta.md",
    "01_descoberta_guiada.md",
    "02_escopo_requisitos.md",
    "03_stack_integracoes.md",
    "04_estimativa_viabilidade.md",
    "05_comunicacao_handoff.md",
    "06_checklist_pre_kickoff.md",
]


def ensure_structure(repo_root: Path) -> None:
    dirs = [
        "protocol",
        "prompts",
        "agents",
        "templates",
        "templates/client_packet",
        "docs",
        "docs/decisions",
        "memory/projects",
        "memory/patterns",
        "memory/lessons",
        "memory/architectures",
        "memory/anti_patterns",
        "memory/best_practices",
        "schemas",
        "config",
    ]
    for directory in dirs:
        (repo_root / directory).mkdir(parents=True, exist_ok=True)

    for doc in REQUIRED_DOCS:
        path = repo_root / "docs" / doc
        if not path.exists():
            path.write_text(f"# {doc}\n\nGenerated by pipeline.\n", encoding="utf-8")

    for name, content in _default_template_packet_content().items():
        path = repo_root / "templates" / "client_packet" / name
        if not path.exists():
            path.write_text(content, encoding="utf-8")

    adr1 = repo_root / "docs" / "decisions" / "ADR-0001.md"
    if not adr1.exists():
        adr1.write_text("# ADR-0001\n\nInitial architecture decision.\n", encoding="utf-8")

    mcp_path = repo_root / "config" / "mcp-servers.json"
    if not mcp_path.exists():
        mcp_path.write_text(
            json.dumps(
                {
                    "mcpServers": {
                        "context7": {"command": "npx", "args": ["@upstash/context7-mcp"]},
                        "sequential-thinking": {
                            "command": "npx",
                            "args": ["@modelcontextprotocol/server-sequential-thinking"],
                        },
                    }
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    tooling_path = repo_root / "config" / "tooling.yaml"
    if not tooling_path.exists():
        tooling_path.write_text(
            "\n".join(
                [
                    "integrations:",
                    "  context7:",
                    "    enabled: true",
                    "  sequential_thinking:",
                    "    enabled: true",
                    "  sonarqube:",
                    "    enabled: true",
                    "",
                    "policies:",
                    "  enforce_document_protocol: true",
                    "  require_three_test_layers: true",
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    decision_policy_path = repo_root / "config" / "decision_policy.json"
    if not decision_policy_path.exists():
        decision_policy_path.write_text(
            json.dumps(
                {
                    "version": "1.1.0",
                    "thresholds": {
                        "go_min_score": 0.78,
                        "go_with_caveats_min_score": 0.52,
                        "go_max_ambiguity_score": 0.45,
                        "go_max_open_gaps": 2,
                        "no_go_max_score": 0.40,
                        "no_go_min_open_gaps": 7,
                        "no_go_min_ambiguity_score": 0.88,
                    },
                    "labels": {
                        "go": "GO",
                        "go_with_caveats": "GO_COM_RESSALVAS",
                        "no_go": "NO_GO",
                    },
                    "segment_thresholds": {
                        "frontend": {
                            "thresholds": {
                                "go_min_score": 0.76,
                                "go_with_caveats_min_score": 0.50,
                                "go_max_ambiguity_score": 0.42,
                                "go_max_open_gaps": 2,
                                "no_go_max_score": 0.38,
                                "no_go_min_open_gaps": 6,
                                "no_go_min_ambiguity_score": 0.85,
                            }
                        },
                        "backend": {
                            "thresholds": {
                                "go_min_score": 0.80,
                                "go_with_caveats_min_score": 0.54,
                                "go_max_ambiguity_score": 0.40,
                                "go_max_open_gaps": 2,
                                "no_go_max_score": 0.40,
                                "no_go_min_open_gaps": 6,
                                "no_go_min_ambiguity_score": 0.84,
                            }
                        },
                        "automacao": {
                            "thresholds": {
                                "go_min_score": 0.74,
                                "go_with_caveats_min_score": 0.50,
                                "go_max_ambiguity_score": 0.48,
                                "go_max_open_gaps": 3,
                                "no_go_max_score": 0.36,
                                "no_go_min_open_gaps": 7,
                                "no_go_min_ambiguity_score": 0.86,
                            }
                        },
                        "fullstack": {
                            "thresholds": {
                                "go_min_score": 0.79,
                                "go_with_caveats_min_score": 0.53,
                                "go_max_ambiguity_score": 0.44,
                                "go_max_open_gaps": 2,
                                "no_go_max_score": 0.39,
                                "no_go_min_open_gaps": 7,
                                "no_go_min_ambiguity_score": 0.87,
                            }
                        },
                    },
                    "calibration": {
                        "min_samples_per_segment": 5,
                        "history_file": "docs/audits/proposal_decision_history.jsonl",
                        "window_days": 90,
                        "min_score_spread": 0.08,
                        "min_ambiguity_spread": 0.08,
                        "last_calibrated_at": None,
                    },
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    stage_validation_policy_path = repo_root / "config" / "stage_validation.json"
    if not stage_validation_policy_path.exists():
        stage_validation_policy_path.write_text(
            json.dumps(
                {
                    "version": "1.0.0",
                    "require_stage_validation_ok": True,
                    "require_handoff_packet": True,
                    "require_contract_loaded": True,
                    "require_notes_present": True,
                    "require_artifacts_exist": True,
                    "block_on_any_missing": True,
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    agent_training_policy_path = repo_root / "config" / "agent_training.json"
    if not agent_training_policy_path.exists():
        agent_training_policy_path.write_text(
            json.dumps(
                {
                    "version": "1.0.0",
                    "history_file": "docs/audits/agent_score_history.jsonl",
                    "leaderboard_file": "docs/audits/agent_leaderboard.json",
                    "shadow_report_file": "docs/audits/shadow_mode_report.json",
                    "weights": {
                        "execution_success": 0.30,
                        "stage_validation": 0.25,
                        "handoff_quality": 0.20,
                        "audit_success": 0.15,
                        "artifact_coverage": 0.10,
                    },
                    "thresholds": {
                        "promotion_score": 0.90,
                        "watch_score": 0.85,
                        "min_runs_for_promotion": 3,
                    },
                    "leaderboard": {
                        "window_days": 30,
                        "min_runs": 2,
                    },
                    "shadow_mode": {
                        "enabled": True,
                        "mode": "autopilot_full",
                        "profile": "shadow_autopilot_full",
                    },
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    sonar_path = repo_root / "sonar-project.properties"
    if not sonar_path.exists():
        sonar_path.write_text(
            "\n".join(
                [
                    "sonar.projectKey=ai-engineering-system",
                    "sonar.sources=src",
                    "sonar.tests=tests",
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    package_json_path = repo_root / "package.json"
    if not package_json_path.exists():
        package_json_path.write_text(
            json.dumps(
                {
                    "name": "ai-engineering-system",
                    "version": "1.0.0",
                    "description": "AI engineering system bootstrap package",
                    "scripts": {
                        "test:python": "python -m pytest",
                        "quality:python": "python scripts/quality_check.py",
                        "runtime:check": "python scripts/runtime_check.py",
                        "audit:safety": "python scripts/release_safety_audit.py",
                        "policy:calibrate": "python scripts/decision_policy_calibration.py --write-policy",
                        "agents:leaderboard": "python scripts/agent_leaderboard.py",
                        "templates:init": "python scripts/init_client_templates.py",
                        "sonar:up": "docker compose --profile tooling up -d sonarqube",
                        "sonar:down": "docker compose --profile tooling down",
                    },
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    communication_protocol_path = repo_root / "protocol" / "AGENT_COMMUNICATION_PROTOCOL.md"
    if not communication_protocol_path.exists():
        communication_protocol_path.write_text(
            "\n".join(
                [
                    "# Agent Communication Protocol",
                    "",
                    "## Communication Contract",
                    "- Every stage must publish a handoff_packet.",
                    "- handoff_packet includes summary, assumptions, risks, open_questions and validation_snapshot.",
                    "",
                    "## Handoff Rules",
                    "- to_agent_id must match contract handoff.",
                    "- Last stage uses empty to_agent_id.",
                    "",
                    "## Validation Snapshot",
                    "- handoff_packet.validation_snapshot is mandatory and audit-ready.",
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    validation_rules_path = repo_root / "protocol" / "VALIDATION_RULES.md"
    if not validation_rules_path.exists():
        validation_rules_path.write_text(
            "\n".join(
                [
                    "# Validation Rules",
                    "",
                    "## Stage Gate",
                    "- Every stage must return stage_validation_ok=true before the next stage runs.",
                    "- Missing contract, missing notes, invalid handoff_packet or missing artifacts block the pipeline.",
                    "",
                    "## Ship Gate",
                    "- SHIP requires all technical checks and stage validation checks green.",
                ]
            )
            + "\n",
            encoding="utf-8",
        )


def required_doc_paths(repo_root: Path) -> list[Path]:
    return [repo_root / "docs" / doc for doc in REQUIRED_DOCS]


def required_template_packet_paths(repo_root: Path) -> list[Path]:
    return [repo_root / "templates" / "client_packet" / name for name in TEMPLATE_PACKET_FILES]


def _default_template_packet_content() -> dict[str, str]:
    return {
        "00_intake_proposta.md": "\n".join(
            [
                "# Intake de Proposta",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "- owner_name: {{OWNER_NAME}}",
                "- created_at_utc: {{CREATED_AT_UTC}}",
                "",
                "## Problema de negocio",
                "- problema_atual:",
                "- impacto_hoje:",
                "- resultado_esperado_90_dias:",
                "",
                "## Contexto",
                "- publico_alvo:",
                "- stakeholders:",
                "- processo_atual:",
                "",
                "## Restricoes",
                "- prazo_alvo:",
                "- orcamento_alvo:",
                "- compliance_seguranca:",
                "",
                "## Criterios de sucesso",
                "- kpi_1:",
                "- kpi_2:",
                "- definicao_de_pronto:",
                "",
                "## Checklist de preenchimento",
                "- [ ] Problema de negocio descrito em linguagem objetiva",
                "- [ ] Prazo e orcamento documentados",
                "- [ ] Criterios de sucesso com KPI mensuravel",
            ]
        )
        + "\n",
        "01_descoberta_guiada.md": "\n".join(
            [
                "# Descoberta Guiada",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "",
                "## Perguntas obrigatorias",
                "- Qual problema deve ser resolvido primeiro?",
                "- Quais usuarios sao impactados na primeira entrega?",
                "- Qual fluxo minimo ponta a ponta deve funcionar no MVP?",
                "- Quais integracoes sao obrigatorias no go-live?",
                "- Quais riscos podem bloquear o kickoff?",
                "",
                "## Respostas coletadas",
                "- pergunta_1:",
                "- pergunta_2:",
                "- pergunta_3:",
                "- pergunta_4:",
                "- pergunta_5:",
                "",
                "## Gaps abertos",
                "- gap_1:",
                "- gap_2:",
                "- gap_3:",
                "",
                "## Acao",
                "- responsavel_para_fechar_gaps:",
                "- prazo_para_fechamento:",
            ]
        )
        + "\n",
        "02_escopo_requisitos.md": "\n".join(
            [
                "# Escopo e Requisitos",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "",
                "## Escopo inicial",
                "- item_1:",
                "- item_2:",
                "- item_3:",
                "",
                "## Fora de escopo",
                "- item_1:",
                "- item_2:",
                "",
                "## Requisitos funcionais",
                "- RF-001:",
                "- RF-002:",
                "- RF-003:",
                "",
                "## Requisitos nao funcionais",
                "- RNF-001:",
                "- RNF-002:",
                "- RNF-003:",
                "",
                "## Regras de negocio",
                "- regra_1:",
                "- regra_2:",
                "- regra_3:",
            ]
        )
        + "\n",
        "03_stack_integracoes.md": "\n".join(
            [
                "# Stack e Integracoes",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "",
                "## Stack proposta",
                "- frontend:",
                "- backend:",
                "- banco_dados:",
                "- automacao_orquestracao:",
                "- observabilidade:",
                "",
                "## Integracoes externas",
                "- integracao_1:",
                "- integracao_2:",
                "- integracao_3:",
                "",
                "## Credenciais e acessos",
                "- owner_credenciais:",
                "- ambiente_homologacao:",
                "- ambiente_producao:",
                "",
                "## Dependencias criticas",
                "- dependencia_1:",
                "- dependencia_2:",
            ]
        )
        + "\n",
        "04_estimativa_viabilidade.md": "\n".join(
            [
                "# Estimativa e Viabilidade",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "",
                "## Viabilidade",
                "- classificacao: alta | media | baixa",
                "- justificativa:",
                "",
                "## Estimativa",
                "- duracao_min_semanas:",
                "- duracao_media_semanas:",
                "- duracao_max_semanas:",
                "- faixa_investimento:",
                "",
                "## Decisao comercial",
                "- decisao: GO | GO_COM_RESSALVAS | NO_GO",
                "- motivos:",
                "",
                "## Riscos principais",
                "- risco_1:",
                "- risco_2:",
                "- risco_3:",
                "",
                "## Plano de mitigacao",
                "- acao_1:",
                "- acao_2:",
            ]
        )
        + "\n",
        "05_comunicacao_handoff.md": "\n".join(
            [
                "# Plano de Comunicacao e Handoff",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "",
                "## Cadencia",
                "- daily_or_weekly:",
                "- canal_principal:",
                "- canal_secundario:",
                "",
                "## Responsaveis",
                "- owner_cliente:",
                "- owner_tecnico:",
                "- owner_projeto:",
                "",
                "## Padrao de handoff",
                "- resumo_executivo:",
                "- decisoes_tomadas:",
                "- riscos_abertos:",
                "- duvidas_abertas:",
                "- proxima_acao:",
                "",
                "## Regras",
                "- [ ] Nao seguir etapa sem validacao completa",
                "- [ ] Toda mudanca relevante deve ter evidencia",
                "- [ ] Toda pendencia deve ter owner e prazo",
            ]
        )
        + "\n",
        "06_checklist_pre_kickoff.md": "\n".join(
            [
                "# Checklist Pre-Kickoff",
                "",
                "- client_name: {{CLIENT_NAME}}",
                "- project_name: {{PROJECT_NAME}}",
                "",
                "## Validacao obrigatoria",
                "- [ ] Objetivo de negocio aprovado pelo decisor",
                "- [ ] Escopo e fora de escopo assinados",
                "- [ ] Requisitos funcionais e nao funcionais completos",
                "- [ ] Stack e integracoes aprovadas",
                "- [ ] Estimativa e viabilidade aprovadas",
                "- [ ] Riscos com mitigacao e owner definidos",
                "- [ ] Plano de comunicacao alinhado",
                "",
                "## Gate final",
                "- kickoff_ready: true | false",
                "- bloqueios_abertos:",
                "- observacoes:",
            ]
        )
        + "\n",
    }
