from __future__ import annotations

import json
from pathlib import Path


REQUIRED_DOCS = [
    "01_visao.md",
    "02_requisitos.md",
    "03_regras_de_negocio.md",
    "04_fluxos.md",
    "05_arquitetura.md",
    "06_modelo_dados.md",
    "07_api.md",
    "08_seguranca.md",
    "09_riscos.md",
    "10_backlog.md",
    "11_validacao.md",
    "12_roadmap.md",
    "13_deploy.md",
    "14_observability.md",
    "15_security_threats.md",
    "16_release_notes.md",
    "27_descoberta_guiada.md",
    "28_validacao_pre_kickoff.md",
    "31_politica_decisao_comercial.md",
]


def ensure_structure(repo_root: Path) -> None:
    dirs = [
        "protocol",
        "prompts",
        "agents",
        "docs",
        "docs/decisions",
        "memory/projects",
        "memory/patterns",
        "memory/lessons",
        "memory/architectures",
        "memory/anti_patterns",
        "memory/best_practices",
        "schemas",
        "config",
    ]
    for directory in dirs:
        (repo_root / directory).mkdir(parents=True, exist_ok=True)

    for doc in REQUIRED_DOCS:
        path = repo_root / "docs" / doc
        if not path.exists():
            path.write_text(f"# {doc}\n\nGenerated by pipeline.\n", encoding="utf-8")

    adr1 = repo_root / "docs" / "decisions" / "ADR-0001.md"
    if not adr1.exists():
        adr1.write_text("# ADR-0001\n\nInitial architecture decision.\n", encoding="utf-8")

    mcp_path = repo_root / "config" / "mcp-servers.json"
    if not mcp_path.exists():
        mcp_path.write_text(
            json.dumps(
                {
                    "mcpServers": {
                        "context7": {"command": "npx", "args": ["@upstash/context7-mcp"]},
                        "sequential-thinking": {
                            "command": "npx",
                            "args": ["@modelcontextprotocol/server-sequential-thinking"],
                        },
                    }
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    tooling_path = repo_root / "config" / "tooling.yaml"
    if not tooling_path.exists():
        tooling_path.write_text(
            "\n".join(
                [
                    "integrations:",
                    "  context7:",
                    "    enabled: true",
                    "  sequential_thinking:",
                    "    enabled: true",
                    "  sonarqube:",
                    "    enabled: true",
                    "",
                    "policies:",
                    "  enforce_document_protocol: true",
                    "  require_three_test_layers: true",
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    decision_policy_path = repo_root / "config" / "decision_policy.json"
    if not decision_policy_path.exists():
        decision_policy_path.write_text(
            json.dumps(
                {
                    "version": "1.0.0",
                    "thresholds": {
                        "go_min_score": 0.78,
                        "go_with_caveats_min_score": 0.52,
                        "go_max_ambiguity_score": 0.45,
                        "go_max_open_gaps": 2,
                        "no_go_max_score": 0.40,
                        "no_go_min_open_gaps": 7,
                        "no_go_min_ambiguity_score": 0.88,
                    },
                    "labels": {
                        "go": "GO",
                        "go_with_caveats": "GO_COM_RESSALVAS",
                        "no_go": "NO_GO",
                    },
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    sonar_path = repo_root / "sonar-project.properties"
    if not sonar_path.exists():
        sonar_path.write_text(
            "\n".join(
                [
                    "sonar.projectKey=ai-engineering-system",
                    "sonar.sources=src",
                    "sonar.tests=tests",
                ]
            )
            + "\n",
            encoding="utf-8",
        )


def required_doc_paths(repo_root: Path) -> list[Path]:
    return [repo_root / "docs" / doc for doc in REQUIRED_DOCS]
